sudo: required
services:
  - docker

before_install:
  - docker build -t samot/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run samot/react-test npm test -- --coverage


after_success:
  - docker build -t samot/multi-client ./client
  - docker build -t samot/multi-nginx ./nginx
  - docker build -t samot/multi-server ./server
  - docker build -t samot/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push samot/multi-client
  - docker push samot/multi-nginx
  - docker push samot/multi-server
  - docker push samot/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-405707153721
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
